services:
    database:
        image: postgres:18.1-alpine3.23
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - order-panel-network

volumes:
    node_modules:
    database-data:
        name: ${APP_NAMESPACE}-database-data

networks:
    order-panel-network:
        name: ${APP_NAMESPACE}-network
        driver: bridge