services:
    database:
        container_name: database
        image: postgres:18.1-alpine3.23
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - order-panel-network

volumes:
    node_modules:
    backend-vendor:
    database-data:

networks:
    order-panel-network:
        name: order-panel-network
        driver: bridge